//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_default p__default;
        
        private static SteamVR_Input_ActionSet_platformer p_platformer;
        
        private static SteamVR_Input_ActionSet_buggy p_buggy;
        
        private static SteamVR_Input_ActionSet_mixedreality p_mixedreality;
        
        private static SteamVR_Input_ActionSet_sliding p_sliding;
        
        private static SteamVR_Input_ActionSet_climbing p_climbing;
        
        private static SteamVR_Input_ActionSet_teleportBall p_teleportBall;
        
        private static SteamVR_Input_ActionSet_thruster p_thruster;
        
        private static SteamVR_Input_ActionSet_pointFollow p_pointFollow;
        
        public static SteamVR_Input_ActionSet_default _default
        {
            get
            {
                return SteamVR_Actions.p__default.GetCopy<SteamVR_Input_ActionSet_default>();
            }
        }
        
        public static SteamVR_Input_ActionSet_platformer platformer
        {
            get
            {
                return SteamVR_Actions.p_platformer.GetCopy<SteamVR_Input_ActionSet_platformer>();
            }
        }
        
        public static SteamVR_Input_ActionSet_buggy buggy
        {
            get
            {
                return SteamVR_Actions.p_buggy.GetCopy<SteamVR_Input_ActionSet_buggy>();
            }
        }
        
        public static SteamVR_Input_ActionSet_mixedreality mixedreality
        {
            get
            {
                return SteamVR_Actions.p_mixedreality.GetCopy<SteamVR_Input_ActionSet_mixedreality>();
            }
        }
        
        public static SteamVR_Input_ActionSet_sliding sliding
        {
            get
            {
                return SteamVR_Actions.p_sliding.GetCopy<SteamVR_Input_ActionSet_sliding>();
            }
        }
        
        public static SteamVR_Input_ActionSet_climbing climbing
        {
            get
            {
                return SteamVR_Actions.p_climbing.GetCopy<SteamVR_Input_ActionSet_climbing>();
            }
        }
        
        public static SteamVR_Input_ActionSet_teleportBall teleportBall
        {
            get
            {
                return SteamVR_Actions.p_teleportBall.GetCopy<SteamVR_Input_ActionSet_teleportBall>();
            }
        }
        
        public static SteamVR_Input_ActionSet_thruster thruster
        {
            get
            {
                return SteamVR_Actions.p_thruster.GetCopy<SteamVR_Input_ActionSet_thruster>();
            }
        }
        
        public static SteamVR_Input_ActionSet_pointFollow pointFollow
        {
            get
            {
                return SteamVR_Actions.p_pointFollow.GetCopy<SteamVR_Input_ActionSet_pointFollow>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p__default = ((SteamVR_Input_ActionSet_default)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_default>("/actions/default")));
            SteamVR_Actions.p_platformer = ((SteamVR_Input_ActionSet_platformer)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_platformer>("/actions/platformer")));
            SteamVR_Actions.p_buggy = ((SteamVR_Input_ActionSet_buggy)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_buggy>("/actions/buggy")));
            SteamVR_Actions.p_mixedreality = ((SteamVR_Input_ActionSet_mixedreality)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_mixedreality>("/actions/mixedreality")));
            SteamVR_Actions.p_sliding = ((SteamVR_Input_ActionSet_sliding)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_sliding>("/actions/sliding")));
            SteamVR_Actions.p_climbing = ((SteamVR_Input_ActionSet_climbing)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_climbing>("/actions/climbing")));
            SteamVR_Actions.p_teleportBall = ((SteamVR_Input_ActionSet_teleportBall)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_teleportBall>("/actions/teleportBall")));
            SteamVR_Actions.p_thruster = ((SteamVR_Input_ActionSet_thruster)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_thruster>("/actions/thruster")));
            SteamVR_Actions.p_pointFollow = ((SteamVR_Input_ActionSet_pointFollow)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_pointFollow>("/actions/pointFollow")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions._default,
                    SteamVR_Actions.platformer,
                    SteamVR_Actions.buggy,
                    SteamVR_Actions.mixedreality,
                    SteamVR_Actions.sliding,
                    SteamVR_Actions.climbing,
                    SteamVR_Actions.teleportBall,
                    SteamVR_Actions.thruster,
                    SteamVR_Actions.pointFollow};
        }
    }
}
